=head1 CONCEPT

英語かくのがつらいので日本語でコンセプトをしるす。

- FormGeneration は必要だ。
-- 工数を削減できる。
- FormGenerator が validation を直接うけもつ必要はない
-- FormValidator::Lite に delegate すればいい
- 依存はすくなく
- YAML からのフォーム生成もできるとよい
- DSL による生成は必須
- csrf 対策
- imager 連携(optional)
- TT には依存しない

=head1 DESIGN ISSUE

=head2 Filter は1クラス1フィルタにするか

基本的には、1クラス1フィルタで、動的にロードすればいい。

